# Generated by Django 2.2.15 on 2020-11-01 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url_video', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('occasion_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email_client', models.EmailField(max_length=254)),
                ('order_state', models.IntegerField(choices=[(1, 'APROBADO'), (2, 'RECHAZADA'), (3, 'PEDIENTE'), (4, 'FALLIDA')], default=1)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9999999. Up to 10-15 digits allowed', regex='\\+?1?\\d{9,15}$')])),
                ('is_public', models.BooleanField(default=False)),
                ('to', models.CharField(max_length=50)),
                ('from_client', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(max_length=300)),
                ('pay_method', models.IntegerField(choices=[(1, 'PAYCO'), (2, 'TC')], default=1)),
                ('talent_response', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'ACEPTADO'), (3, 'RECHAZADO'), (4, 'EN PROCESO'), (5, 'FINALIZADO')], default=1)),
                ('order_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=19)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Occasion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
