# Generated by Django 2.2.15 on 2020-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200928_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.IntegerField(choices=[(1, 'APROBADO'), (2, 'RECHAZADA'), (3, 'PEDIENTE'), (4, 'FALLIDA')], default=1),
        ),
    ]
