from .categories_serializer import CategorySerializer
from .categories_serializer import SubCategoryCustomSerializer, SubCategorySerializer
from .client_serializers import ClientSerializer
from .talent_serializer import TalentSerializer, TalentUpdateSerializer
from .user_serializer import UserSerializer, CustomTokenObtainPairSerializer
