# Generated by Django 2.2.12 on 2020-06-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_category_client_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='categories',
            field=models.ManyToManyField(related_name='talent_category', to='users.Category'),
        ),
    ]
