# Generated by Django 2.2.12 on 2020-06-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200613_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'A category with that name already exist'}, max_length=30, unique=True, verbose_name='Category'),
        ),
    ]
