# Generated by Django 2.2.12 on 2020-06-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200622_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.related.OneToOneField>', unique=True),
        ),
    ]
