# Generated by Django 2.2.12 on 2020-06-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_talent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
