# Generated by Django 2.2.12 on 2020-06-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200625_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
