# Generated by Django 2.2.15 on 2020-11-01 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201101_1037'),
        ('balance', '0003_balancetalent_talent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.BalanceOrder')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
