# Generated by Django 2.2.15 on 2020-11-08 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_repay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('state_withdraw', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'PAGADA'), (3, 'RECHAZADA')], default=1)),
                ('balance_talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.BalanceTalent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
