# Generated by Django 2.2.15 on 2020-11-01 15:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exist'}, max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9999999. Up to 10-15 digits allowed', regex='\\+?1?\\d{9,15}$')])),
                ('where_find_you', models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Twitter'), (4, 'YouTube'), (5, 'TikTok'), (6, 'Twitch'), (7, 'Otro')], default=1)),
                ('username', models.CharField(max_length=15)),
                ('followers', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
