# Generated by Django 2.2.15 on 2020-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='full_name',
            field=models.CharField(default='prueba', max_length=50),
            preserve_default=False,
        ),
    ]
